### ISSUE TITLE
Plugin not working in Vue + Webpack

### ISSUE THREAD

**Issue by sinemacula-ben** [vueuse/schema-org#41] opened 2023-03-08 09:49 UTC
Hi Harlan - apologies for another issue... Again, I must be missing something really obvious because no one else seems to be having issues...

For some reason, I cannot get this to update/insert the schema into the DOM. There are no errors thrown and the debug component correctly shows my initially loaded `ld+json` content from my HTML template.

At present, my testing configuration looks like this (`./app.js`):

```ts
import { createHead } from '@vueuse/head';
import { SchemaOrgUnheadPlugin } from '@vueuse/schema-org';

const head = createHead();

head.use(SchemaOrgUnheadPlugin);
app.use(head);
```

And then I have added a whole bunch of tests (`./App.vue`):

```vue
<script setup>
    import { SchemaOrgWebPage } from '@vueuse/schema-org';
</script>
<template>
    <schema-org-web-page
        type="AboutPage"
        name="About Us"
    />
</template>
```

An example view (`./views/Test-1.vue`):

```vue
<script setup>
    import { SchemaOrgOrganization, SchemaOrgWebSite, SchemaOrgWebPage, SchemaOrgDebug } from '@vueuse/schema-org';
</script>
<template>
    <schema-org-organization
        name="Nuxt.js"
        logo="/logo.png"
        same-as="['https://twitter.com/nuxt_js']"
    />
    <schema-org-web-site name="Nuxt" />
    <schema-org-web-page />
    <schema-org-debug />
</template>

<script setup>
    import { SchemaOrgOrganization, SchemaOrgWebSite, SchemaOrgWebPage, SchemaOrgDebug } from '@vueuse/schema-org';
</script>
```

Forgive me for posting here, but I have literally re-read the documentation 50 times and tried everything that I could think of that might be preventing this from working.

Things I have tried:

- Both components and composition methods
- Initialising `createHead` and `SchemaOrgUnheadPlugin` outside of my wrapper class (illustrated in example above)
- The debug component correctly shows the content from my initial `ld+json` so this seems to be working correctly
- I removed my initial `ld+json` just in case it was getting confused
- I added configuration for `host` and `meta` in the initial `SchemaOrgUnheadPlugin` setup but given this isn't SSR (yet), I didn't think this was necessary - it didn't work anyway
- I tried running in both `dev` and `prod` - neither work

I am guessing that perhaps this is to do with the fact that I am using Webpack, not Vite - I haven't made the migration yet as have been using Webpack for years and am very happy with it.

Can you suggest anything else I can try or a way I can further debug what is happening? It's odd that I am not receiving any errors despite it not updating the schema

**Comment by harlan-zw** [comment] 2023-03-08 12:21
Hey @sinemacula-ben, not a problem, happy to help :)

So the issue is that you're inspecting the HTML and you can't see the generated schema.org, but it's appearing in the `SchemaOrgDebug` component?

This may be a dumb question, but did you check the end of body? You may be looking for it in the `<head>` but it's not inserted there for avoid blocking the render.

**Comment by sinemacula-ben** [comment] 2023-03-08 12:55
Hey @harlan-zw - Sorry, bad communication from me. I can see the contents of my originally loaded `ld+json` - as in the data that is hardcoded in my HTML template (not inserted by the plugin).

On my `index.ejs` template, I have an 'initial' `ld+json` element like so (this is temporary):

```
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "<%= config.app.name %>",
        "url": "<%= config.app.urls.app %>",
        "logo": "<%= require('static/assets/images/brand/logo-type-blue.png') %>",
        "sameAs": [<%= '"' + Object.values(config.company.social).map(x => x.url).join('","') + '"' %>]
    }
</script>
```

The above is successfully read into the `SchemaOrgDebug` component - I imagine the component is just reading from a query selector for `application/ld+json` so this probably doesn't mean much.

I have been trying to debug further, and this is where I am at:

- Building in `production` seems to _contribute_ to the cause because of the following lines extracted from `@unhead/vue/dist/index.mjs`:

```
if (process.env.NODE_ENV !== "development" && typeof window !== "undefined") {
if (isSPA === null && !window.document.querySelector("#schema-org-graph"))
  isSPA = true;
if (!isSPA)
  return;
}
```

- I think my initial `application/ld+json` element in my `index.ejs` template is causing issues because it does not have the key and id that the payload expects. See here:

```
return useHead({
    script: [
        {
            type: "application/ld+json",
            id: "schema-org-graph",
            key: "schema-org-graph",
            // @ts-expect-error runtime type
            nodes: input
        }
    ]
}, { mode: isSPA ? "all" : "server" });
```

- By removing the initial element, we have progress... A new `application/ld+json` element is inserted into the head. However, it is not rendered correctly. See the following:

`<script type="application/ld+json" id="schema-org-graph" nodes="[object Object]"></script>`

I believe I am close but not quite there. For some reason, `nodes` is not working in the way it is meant to (I'm not familiar with that property so no sure what the payload should be). I have played around with it with things like so (i.e. no plugin):

```
useHead({
    script: [
        {
            type: 'application/ld+json',
            id: 'schema-org-graph',
            key: 'schema-org-graph',
            nodes: [ defineWebSite({ name: 'Nuxt' }) ]
        }
    ]
}, { mode: 'all' });
```

But this yields the above result as well... I'll keep going - frustratingly, I know there will be something really obvious I am missing otherwise, others would have posted issues as well

**Comment by sinemacula-ben** [comment] 2023-03-08 13:14
@harlan-zw - I have a further update...

In the above tests, I was using the following configuration:

`head.use(SchemaOrgUnheadPlugin);`

By updating the configuration to the following, the `nodes="[object Object]"` is gone, and we successfully have content in the `script` element:

`head.use(SchemaOrgUnheadPlugin({}, () => {}));`

The issue I now have is that I don't know what configuration to insert into the above - if any... I have seen the `UserConfig` documentation but I cannot find any reference to the second callback. I assume it instructs the plugin how to read the data from a route based on the example in the docs but I am not certain. Could you advise what the second parameter actually does?

**Comment by harlan-zw** [comment] 2023-03-13 13:14
> @harlan-zw - I have a further update...
> 
> In the above tests, I was using the following configuration:
> 
> `head.use(SchemaOrgUnheadPlugin);`
> 
> By updating the configuration to the following, the `nodes="[object Object]"` is gone, and we successfully have content in the `script` element:
> 
> `head.use(SchemaOrgUnheadPlugin({}, () => {}));`
> 
> The issue I now have is that I don't know what configuration to insert into the above - if any... I have seen the `UserConfig` documentation but I cannot find any reference to the second callback. I assume it instructs the plugin how to read the data from a route based on the example in the docs but I am not certain. Could you advise what the second parameter actually does?

This was the solution if anyone else comes across this, closing.

**Closed by harlan-zw** 2023-03-13 13:14 UTC
