### ISSUE TITLE
Empty schema with SSR & renderHeadToString()

### ISSUE THREAD

**Issue by Fy-** [vueuse/schema-org#32] opened 2022-11-16 00:44 UTC
The schema is always empty in bodyTags when I call renderHeadToString() from @vueuse/head.

https://stackblitz.com/edit/vitejs-vite-krgcr3 

```
bodyTags: '<script type="application/ld+json" data-id="schema-org-graph">{\n' +
  '  "@context": "https://schema.org",\n' +
  '  "@graph": []\n' +
  '}</script>',
```
It works on the client side:
```
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@id": "https://google.com/#identity",
      "@type": "Organization",
      "name": "test",
      "url": "https://google.com"
    },
  //...
}`
```

**Comment by harlan-zw** [comment] 2022-11-16 05:34
Hey @Fy- 

Thanks for the issue and reproduction!

I can indeed replicate the issue, I have a solution in mind but it will require migrating the @vueuse/schema-org core to use the latest  @vueuse/head. May be a couple of days before I have that ready

**Comment by markmartirosian** [comment] 2022-11-30 20:15
Encountered this on 1.1.0-beta.6

**Comment by markmartirosian** [comment] 2022-11-30 20:20
One more thing that may be related, changing `UserConfig` `position` does nothing.

**Comment by harlan-zw** [comment] 2022-12-07 13:12
Thanks for your patience.

This seems to be fixed with v2, you can find a working version of your reproduction here: https://stackblitz.com/edit/vitejs-vite-hv2mlz?file=package.json

Let me know if you have any issues with the migration

**Closed by harlan-zw** 2022-12-07 13:12 UTC
